### PR TITLE
Support binding types that implement text encoding

### PR DESCRIPTION
**Pull request by devnev**
I ran across this interface while trying to create a flag from a logrus.Level values, and thought it might make sense to support it directly in flagbind.

### CODE REVIEW

**Comment by devnev** [comment]
ping @AdamSLevy

**Comment by devnev** [comment]
@AdamSLevy mind if I reopen this against `main`?

**Comment by AdamSLevy** [comment]
@devnev Yes please. Thank you for the PR. Apologies for not responding previously, I took a break from work up until recently.

**Comment by AdamSLevy** [comment]
I changed to default branch to 'main' but did it the "wrong" way in github, which caused this to be auto closed.

**Pull request closed without merging**
